In [1]:
# Import Modules
import os
import csv
import pathlib
import pandas as pd

#Set path for file and open the csv
csvpath = os.path.join('..', 'Chicago_Energy_Benchmarking_20240408.csv')

with open(csvpath) as csvfile:
    buildingenergydata = pd.read_csv(csvfile)

In [2]:
#Filter to just the Year, Property Name, and weather Normalized Source EUI and Total GHG Emissions columns

filtered_bedata = buildingenergydata[['Data Year', 'Property Name', 'Weather Normalized Source EUI (kBtu/sq ft)', 'Total GHG Emissions (Metric Tons CO2e)']]

#Rename columns
new_names = {'Data Year': 'Year',
             'Weather Normalized Source EUI (kBtu/sq ft)': 'Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.)',
             'Total GHG Emissions (Metric Tons CO2e)': 'Total Greenhouse Gas Emissions (Metric Tons of Co2e)'}

filtered_bedata = filtered_bedata.rename(columns=new_names)

In [3]:
# Create this table exclusively for several notable buildings
# Filter data for The Art Institute of Chicago exclusively for years 2016, 2018, 2020, and 2022
aic_data = filtered_bedata[filtered_bedata['Property Name'] == 'The Art Institute of Chicago']
aic_data = aic_data[aic_data['Year'].isin([2016, 2018, 2020, 2022])]

#Find change in both quantities ove rtime
aic_diff1 = aic_data['Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.)'].diff()
aic_diff2 = aic_data['Total Greenhouse Gas Emissions (Metric Tons of Co2e)'].diff()

#Add changes to tables
aic_data['Change in Source Energy Use'] = aic_diff1
aic_data['Change in Greenhouse Gas Emissions'] = aic_diff2

aic_data

,Year,Property Name,Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.),Total Greenhouse Gas Emissions (Metric Tons of Co2e),Change in Source Energy Use,Change in Greenhouse Gas Emissions
3989,2016,The Art Institute of Chicago,453.0,25340.9,NaN,NaN
9417,2018,The Art Institute of Chicago,426.5,23960.3,-26.5,-1380.6
16878,2020,The Art Institute of Chicago,390.1,20891.4,-36.4,-3068.9
24107,2022,The Art Institute of Chicago,389.5,19068.8,-0.6,-1822.6

In [4]:
#Filter data for City Hall exclusively for years 2016, 2018, 2020, and 2022

cityhall_data = filtered_bedata[filtered_bedata['Property Name'] == 'City Hall']
cityhall_data = cityhall_data[cityhall_data['Year'].isin([2016, 2018, 2020, 2022])]

#Find change in both quantities ove rtime
city_diff1 = cityhall_data['Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.)'].diff()
city_diff2 = cityhall_data['Total Greenhouse Gas Emissions (Metric Tons of Co2e)'].diff()

#Add changes to tables
cityhall_data['Change in Source Energy Use'] = city_diff1
cityhall_data['Change in Greenhouse Gas Emissions'] = city_diff2

cityhall_data

,Year,Property Name,Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.),Total Greenhouse Gas Emissions (Metric Tons of Co2e),Change in Source Energy Use,Change in Greenhouse Gas Emissions
3671,2016,City Hall,313.9,7097.9,NaN,NaN
10664,2018,City Hall,284.8,6473.4,-29.1,-624.5
14651,2020,City Hall,255.1,5547.1,-29.7,-926.3
23960,2022,City Hall,253.9,5045.1,-1.2,-502.0

In [5]:
#Filter data for NU Chicago Campus exclusively for years 2016, 2018, 2020, and 2022

northwestern_data = filtered_bedata[filtered_bedata['Property Name'] == 'Northwestern University Chicago Campus']
northwestern_data = northwestern_data[northwestern_data['Year'].isin([2016, 2018, 2020, 2022])]

#Find change in both quantities ove rtime
nu_diff1 = northwestern_data['Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.)'].diff()
nu_diff2 = northwestern_data['Total Greenhouse Gas Emissions (Metric Tons of Co2e)'].diff()

#Add changes to tables
northwestern_data['Change in Source Energy Use'] = nu_diff1
northwestern_data['Change in Greenhouse Gas Emissions'] = nu_diff2

northwestern_data

,Year,Property Name,Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.),Total Greenhouse Gas Emissions (Metric Tons of Co2e),Change in Source Energy Use,Change in Greenhouse Gas Emissions
2579,2016,Northwestern University Chicago Campus,581.1,71081.4,NaN,NaN
15349,2020,Northwestern University Chicago Campus,324.6,4055.1,-256.5,-67026.3
21980,2022,Northwestern University Chicago Campus,351.0,3907.2,26.4,-147.9

In [6]:
#Filter data for Swedish Covenant Hospital exclusively for years 2016, 2018, 2020, and 2022

swedishhospital_data = filtered_bedata[filtered_bedata['Property Name'] == 'Swedish Covenant Hospital Campus']
swedishhospital_data = swedishhospital_data[swedishhospital_data['Year'].isin([2016, 2018, 2020, 2022])]

#Find change in both quantities ove rtime
hos_diff1 = swedishhospital_data['Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.)'].diff()
hos_diff2 = swedishhospital_data['Total Greenhouse Gas Emissions (Metric Tons of Co2e)'].diff()

#Add changes to tables
swedishhospital_data['Change in Source Energy Use'] = hos_diff1
swedishhospital_data['Change in Greenhouse Gas Emissions'] = hos_diff2

swedishhospital_data

,Year,Property Name,Median Weather-Normalized Source Energy Use Intensity (kBTU/sq. ft.),Total Greenhouse Gas Emissions (Metric Tons of Co2e),Change in Source Energy Use,Change in Greenhouse Gas Emissions
3051,2016,Swedish Covenant Hospital Campus,475.0,21859.7,NaN,NaN
9722,2018,Swedish Covenant Hospital Campus,445.5,20617.2,-29.5,-1242.5
17506,2020,Swedish Covenant Hospital Campus,427.5,18719.4,-18.0,-1897.8
21343,2022,Swedish Covenant Hospital Campus,412.3,15862.7,-15.2,-2856.7